In [0]:
import numpy as np
from sklearn import svm
from google.colab import files
import ast

In [24]:
uploaded = files.upload()
name = ""
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving front_down_right.txt to front_down_right.txt
Saving front_down_left.txt to front_down_left.txt
Saving to_the_right.txt to to_the_right.txt
Saving to_the_left.txt to to_the_left.txt
Saving default_flat.txt to default_flat (2).txt
User uploaded file "front_down_right.txt" with length 17868 bytes
User uploaded file "front_down_left.txt" with length 19459 bytes
User uploaded file "to_the_right.txt" with length 19532 bytes
User uploaded file "to_the_left.txt" with length 18593 bytes
User uploaded file "default_flat.txt" with length 18097 bytes


In [39]:
data = None
labels = None
print(data, labels)
for name in uploaded.keys():
  arr = np.fromstring(uploaded[name], sep=", ")
  arr = arr.reshape(arr.shape[0]//3, 3)
  if data is None:
    data = arr
  else:
    data = np.vstack([data, arr])
  lab = np.full(arr.shape[0], name)
  if labels is None:
    labels = lab
  else:
    labels = np.concatenate([labels, lab])
print(data, data.shape)
print(labels, labels.shape)


None None
[[ 0.28  9.66  0.27]
 [ 0.15  9.69  0.19]
 [ 0.16  9.69  0.27]
 ...
 [-0.45  0.15  9.61]
 [-0.49  0.19  9.59]
 [-0.52  0.17  9.55]] (5134, 3)
['front_down_right.txt' 'front_down_right.txt' 'front_down_right.txt' ...
 'default_flat.txt' 'default_flat.txt' 'default_flat.txt'] (5134,)


In [0]:

sss = uploaded[fn]
print(sss.strip())
a = np.fromstring(sss, sep=', ')
print(a, a.shape)

b'-0.50, 0.17, 9.45,-0.41, 0.18, 9.54,-0.58, 0.14, 9.57,-0.46, 0.14, 9.51,-0.25, 0.13, 9.84,-0.48, 0.15, 9.55,-0.44, 0.14, 9.45,-0.45, 0.18, 9.53,-0.38, 0.19, 9.43,-0.39, 0.11, 9.78,-0.47, 0.15, 9.45,-0.42, 0.19, 9.48,-0.53, 0.17, 9.31,-0.74, 0.14, 9.08,-0.71, 0.08, 9.01,-0.43, 0.18, 9.59,-0.12, 0.24, 10.18,-0.47, 0.19, 9.59,-0.60, 0.16, 9.57,-0.41, 0.17, 9.63,-0.45, 0.17, 9.59,-0.44, 0.16, 9.58,-0.44, 0.17, 9.59,-0.48, 0.17, 9.57,-0.49, 0.18, 9.40,-0.46, 0.16, 9.51,-0.60, 0.17, 9.54,-0.49, 0.18, 9.55,-0.43, 0.14, 9.48,-0.46, 0.16, 9.54,-0.42, 0.20, 9.48,-0.87, -0.11, 9.30,-0.42, 0.14, 9.53,-0.40, 0.14, 9.54,-0.59, 0.16, 9.57,-0.49, 0.18, 9.51,-0.45, 0.18, 9.57,-0.46, 0.17, 9.53,-0.44, 0.17, 9.50,-0.44, 0.18, 9.46,-0.46, 0.17, 9.49,-0.45, 0.19, 9.48,-0.59, 0.17, 9.57,-0.48, 0.15, 9.56,-0.46, 0.17, 9.52,-0.43, 0.17, 9.56,-0.45, 0.18, 9.56,-0.48, 0.16, 9.56,-0.47, 0.03, 9.54,-0.61, 0.18, 9.47,-0.44, 0.18, 9.56,-0.44, 0.16, 9.51,-0.44, 0.19, 9.49,-0.43, 0.16, 9.55,-0.43, 0.17, 9.52,-0.43,

In [40]:
clf = svm.SVC(gamma='scale')
clf.fit(data, labels )

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [43]:
clf.predict([[0, 9, 0]])

array(['front_down_right.txt'], dtype='<U20')